pub mod kangaroo_twelve;
pub mod cshake;

pub mod bindgen {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]

    // including bindings auto-generated by bindgen
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}